openapi: 3.0.3
info:
  title: Article App API
  version: 1.0.0
  description: API для управления статьями с аутентификацией JWT
servers:
  - url: /api
paths:
  /dev/reset-db:
    post:
      tags:
        - Dev
      summary: Сброс базы данных (только для DEV)
      description: Эндпоинт для полного сброса базы данных. Доступен только в режиме разработки.
      responses:
        '200':
          description: База данных успешно сброшена
        '403':
          description: Операция запрещена в продакшн-режиме
  /auth/register:
    post:
      tags:
        - Auth
      summary: Регистрация нового пользователя (только для DEV)
      description: |
        Эндпоинт регистрации доступен только в режиме разработки.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 32
                  pattern: '^[a-zA-Z0-9_]+$'
                password:
                  type: string
                  minLength: 6
                  maxLength: 128
              required:
                - username
                - password
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    minimum: 1
                  username:
                    type: string
                    minLength: 3
                    maxLength: 32
                    pattern: '^[a-zA-Z0-9_]+$'
        '400':
          description: Некорректные данные или пользователь уже существует
  /auth/login:
    post:
      tags:
        - Auth
      summary: Вход пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 32
                  pattern: '^[a-zA-Z0-9_]+$'
                password:
                  type: string
                  minLength: 6
                  maxLength: 128
              required:
                - username
                - password
      responses:
        '200':
          description: Успешный вход. refresh_token устанавливается в httpOnly cookie.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    minLength: 16
        '401':
          description: Неверные учетные данные

  /auth/refresh:
    post:
      tags:
        - Auth
      summary: Обновление токена доступа
      description: |
        refresh_token должен быть передан в httpOnly cookie.
      responses:
        '200':
          description: Новый access_token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    minLength: 16
        '401':
          description: Недействительный refresh_token

  /media/upload-temp:
    post:
      tags:
        - Media
      summary: Загрузка временного медиафайла
      description: Загружает файл во временное хранилище S3. После создания или обновления статьи, временные файлы переносятся в постоянное хранилище.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Файл успешно загружен
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    format: uri
                    description: Временный URL S3 для загрузки файла
        '401':
          description: Требуется аутентификация

  /articles:
    post:
      tags:
        - Articles
      summary: Создание новой статьи
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 3
                  maxLength: 128
                content:
                  type: string
                  minLength: 1
                  maxLength: 10000
                media:
                  type: array
                  description: Список URL медиафайлов, связанных со статьей
                  items:
                    type: string
                    format: uri
              required:
                - title
                - content
                - media
      responses:
        '201':
          description: Статья создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '401':
          description: Требуется аутентификация

  /articles/{id}:
    get:
      tags:
        - Articles
      summary: Получить статью по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Статья найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '404':
          description: Статья не найдена

    put:
      tags:
        - Articles
      summary: Изменить статью по ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 3
                  maxLength: 128
                content:
                  type: string
                  minLength: 1
                  maxLength: 10000
                media:
                  type: array
                  description: Список URL медиафайлов, связанных со статьей
                  items:
                    type: string
                    format: uri
      responses:
        '200':
          description: Статья обновлена
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    minLength: 1
                    maxLength: 10000
        '401':
          description: Требуется аутентификация
        '404':
          description: Статья не найдена

tags:
  - name: Auth
    description: Методы аутентификации и авторизации
  - name: Articles
    description: Методы для работы со статьями
  - name: Media
    description: Методы для работы с медиафайлами
  - name: Dev
    description: Методы для разработки и тестирования (только для DEV)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        title:
          type: string
          minLength: 3
          maxLength: 128
        content:
          type: string
          minLength: 1
          maxLength: 10000
        author:
          type: string
          minLength: 3
          maxLength: 32
          pattern: '^[a-zA-Z0-9_]+$'
        media:
          type: array
          description: Список URL медиафайлов, связанных со статьей
          items:
            type: string
            format: uri
      required:
        - id
        - title
        - content
        - author
        - media