openapi: 3.0.3
info:
  title: Article App API
  version: 1.0.0
  description: API для управления статьями с аутентификацией JWT
servers:
  - url: /api
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Вход пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '401':
          description: Неверные учетные данные

  /auth/refresh:
    post:
      tags:
        - Auth
      summary: Обновление токена доступа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
                - refresh_token
      responses:
        '200':
          description: Новый access_token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        '401':
          description: Недействительный refresh_token

  /articles:
    post:
      tags:
        - Articles
      summary: Создание новой статьи
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              required:
                - title
                - content
      responses:
        '201':
          description: Статья создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '401':
          description: Требуется аутентификация

  /articles/{id}:
    get:
      tags:
        - Articles
      summary: Получить статью по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Статья найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '404':
          description: Статья не найдена

    put:
      tags:
        - Articles
      summary: Изменить статью по ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Статья обновлена
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
        '401':
          description: Требуется аутентификация
        '404':
          description: Статья не найдена

tags:
  - name: Auth
    description: Методы аутентификации и авторизации
  - name: Articles
    description: Методы для работы со статьями

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        author:
          type: string
      required:
        - id
        - title
        - content
        - author