networks:
  rulehub-net:
    driver: bridge
    attachable: true

volumes:
  rulehub-backend-data:
  postgres-data:
  minio-data:

services:
  rulehub-backend:
    container_name: rulehub-backend
    image: "ghcr.io/nrf24l01/rulehub/rulehub-backend:latest"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:1324/ping"]
      interval: 10s
      retries: 30
      timeout: 3s
      start_period: 10s
    restart: "no"
    ports:
      - "8004:1324"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - MINIO_ENDPOINT=minio:9000
      - MINIO_USERNAME=miniadmin
      - MINIO_PASSWORD=miniadmin
      - MINIO_BUCKET=rulehub
      - TEST_ENV=true
      - RUNTIME_PRODUCTION=true
    depends_on:
      postgres:
        condition: service_healthy
      createbuckets:
        condition: service_started
      minio:
        condition: service_healthy
    volumes:
    - .:/usr/src/app
    networks:
      - rulehub-net

  postgres:
    image: postgres:13-alpine
    container_name: postgres-rulehub
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rulehub-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    command: ["postgres", "-c", "listen_addresses=*"]
  
  minio:
    image: minio/minio:latest
    container_name: minio-rulehub
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    expose:
      - "9000"
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - rulehub-net
  
  createbuckets:
    image: minio/mc
    container_name: minio-rulehub-bucketer
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/rulehub;
      /usr/bin/mc policy set public myminio/rulehub;
      exit 0;
      "
    networks:
      - rulehub-net
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-rulehub-backend
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock