name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логин в GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Приведение имени репозитория к нижнему регистру
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Собираем Docker-образ с кешем
        uses: docker/build-push-action@v5
        with:
          context: backend
          tags: ghcr.io/${{ env.REPO_NAME }}/rulehub-backend:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-tests:
    name: Build Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логин в GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Приведение имени репозитория к нижнему регистру
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Собираем Docker-образ с кешем
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile.test
          tags: ghcr.io/${{ env.REPO_NAME }}/rulehub-backend-tests:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
