name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
  workflow_dispatch:
    
jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логин в GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Приведение имени репозитория к нижнему регистру
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Собираем Docker-образ
        run: |
          docker build \
            -t ghcr.io/${{ env.REPO_NAME }}/rulehub-backend:latest backend/

      - name: Пушим образ в GHCR
        run: docker push ghcr.io/${{ env.REPO_NAME }}/rulehub-backend:latest
  
  build-tests:
    name: Build Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логин в GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Приведение имени репозитория к нижнему регистру
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Собираем Docker-образ
        run: |
          docker build \
            -f backend/Dockerfile.test \
            -t ghcr.io/${{ env.REPO_NAME }}/rulehub-backend-tests:latest backend/

      - name: Пушим образ в GHCR
        run: docker push ghcr.io/${{ env.REPO_NAME }}/rulehub-backend-tests:latest
